name: K6 Tests with Mock API

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  mock-api-tests:
    name: Run K6 Tests with Mock API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm init -y
          npm install express cors

      - name: Create Mock API Server
        run: |
          cat > mock-server.js << 'EOF'
          const express = require('express');
          const cors = require('cors');

          const app = express();
          const PORT = 3000;

          app.use(cors());
          app.use(express.json());

          app.post('/login', (req, res) => {
            const { username, senha } = req.body;
            
            // Simular validação
            if (username === 'julio.lima' && senha === '123456') {
              res.status(200).json({
                token: 'mock-jwt-token-' + Date.now(),
                message: 'Login successful'
              });
            } else {
              res.status(401).json({
                error: 'Invalid credentials'
              });
            }
          });

          app.get('/health', (req, res) => {
            res.status(200).json({ status: 'OK' });
          });

          app.listen(PORT, () => {
            console.log(`Mock API server running on port ${PORT}`);
          });
          EOF

      - name: Start Mock API Server
        run: node mock-server.js &
        env:
          NODE_ENV: test

      - name: Wait for server to start
        run: |
          echo "⏳ Aguardando servidor mock iniciar..."
          sleep 5
          curl -f http://localhost:3000/health || exit 1
          echo "✅ Servidor mock está rodando!"

      - name: Run K6 Iteration Tests
        uses: grafana/k6-action@v0.3.0
        with:
          filename: test/login.interation.test.js
          flags: --out json=results-iterations-mock.json

      - name: Run K6 Virtual Users Tests
        uses: grafana/k6-action@v0.3.0
        with:
          filename: test/login.virtual.users.test.js
          flags: --out json=results-virtual-users-mock.json

      - name: Upload Mock Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: k6-mock-results
          path: results-*-mock.json
          retention-days: 30

      - name: Test Summary
        run: |
          echo "📊 Resumo dos Testes com Mock API:"
          echo "=================================="
          if [ -f results-iterations-mock.json ]; then
            echo "✅ Teste por iterações: COMPLETO"
          else
            echo "❌ Teste por iterações: FALHOU"
          fi

          if [ -f results-virtual-users-mock.json ]; then
            echo "✅ Teste com usuários virtuais: COMPLETO"
          else
            echo "❌ Teste com usuários virtuais: FALHOU"
          fi
